version: '2'
services:  
    auth-service:
        image: vgacisc/cjp2-auth-service
        mem_limit: 800m
        ports: 
          - 8083:8083
        networks:
          - cjp2-network              
        environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres12:5432/vgac
          SPRING_DATASOURCE_USERNAME: vgac
          SPRING_DATASOURCE_PASSWORD: vgac          
        deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s

    alumno-service:
        image: vgacisc/cjp2-alumno-service
        mem_limit: 800m
        ports: 
          - 8082:8082
        networks:
          - cjp2-network  
        environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres12:5432/vgac
          SPRING_DATASOURCE_USERNAME: vgac
          SPRING_DATASOURCE_PASSWORD: vgac
        deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
    postgres12:
        image: postgres:12
        restart: always
        ports:
          - 5432:5432
        networks:
          - cjp2-network
        environment:
          POSTGRES_USER: vgac
          POSTGRES_PASSWORD: vgac   
          PGDATA: /var/lib/postgresql/data/pgdata       
        volumes:
            - ./pgdata:/var/lib/postgresql/data      
        logging:
            driver: "json-file"
            options:
                max-size: "100m" 
        
networks:
  cjp2-network:
        


    
